_wandb:
    value:
        cli_version: 0.22.3
        e:
            3hxgbwtqbty5g43xg9rpknvixecz1d0h:
                codePath: SpeedEstimation\SpeedEstimator_train_v3.py
                codePathLocal: SpeedEstimator_train_v3.py
                cpu_count: 16
                cpu_count_logical: 24
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "894638387200"
                        used: "778183401472"
                email: kkyle0927@kaist.ac.kr
                executable: c:\Users\ChanyoungKo\anaconda3\envs\IIT\python.exe
                git:
                    commit: 9685c214010f410c5d69120acf6e04f477c939d6
                    remote: https://github.com/kkyle0927/IIT.git
                gpu: NVIDIA GeForce RTX 3060 Ti
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 4864
                      memoryTotal: "8589934592"
                      name: NVIDIA GeForce RTX 3060 Ti
                      uuid: GPU-ea59845b-ff8d-48c2-5a7f-69177f0486a9
                host: DESKTOP-JPQ9R9E
                memory:
                    total: "34088464384"
                os: Windows-10-10.0.19045-SP0
                program: C:\Github\IIT\SpeedEstimation\SpeedEstimator_train_v3.py
                python: CPython 3.10.18
                root: C:\Github\IIT\SpeedEstimation
                startedAt: "2026-01-09T04:27:42.610005Z"
                writerId: 3hxgbwtqbty5g43xg9rpknvixecz1d0h
        m: []
        python_version: 3.10.18
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 13
                - 16
            "4": 3.10.18
            "5": 0.22.3
            "8":
                - 3
            "12": 0.22.3
            "13": windows-amd64
L:
    value: 90
S:
    value: 3
accum_steps:
    value: 2
arch:
    value: GRU_Stack
attn_heads:
    value: 1
batch_size:
    value: 1024
cond_names:
    value:
        - accel_sine
        - asym_30deg
        - asym_60deg
        - cadence_120p
        - cadence_90p
        - crouch
        - decline_5deg
        - incline_10deg
        - level_08mps
        - level_12mps
        - level_16mps
cos_T0:
    value: 10
cos_Tmult:
    value: 1
d_model:
    value: 192
data_length:
    value: 12000
dropout_p:
    value: 0.3
eff_batch_size:
    value: 2048
effective_global_bs:
    value: 2048
epochs:
    value: 20
eta_min:
    value: 1e-05
hp:
    value:
        L: 90
        S: 3
        h: 192
        layers: 3
huber_delta:
    value: 0.5
live_plot:
    value: false
lr:
    value: 0.0003
lstm_h:
    value: 512
models:
    value:
        GRU_Stack:
            grid:
                L:
                    - 90
                    - 120
                    - 140
                    - 160
                    - 180
                S:
                    - 3
                h:
                    - 192
                    - 164
                    - 128
                layers:
                    - 3
                    - 2
                    - 1
        SmallTCN_LSTM_Attn:
            grid:
                L:
                    - 91
                S:
                    - 3
                d:
                    - 192
                h:
                    - 192
                kset:
                    - - 5
                      - 3
        TCN_GRU:
            grid:
                L:
                    - 91
                S:
                    - 3
                blocks:
                    - 3
                d:
                    - 192
                h:
                    - 256
                kset:
                    - - 5
                      - 3
        TCN_LSTM:
            grid:
                L:
                    - 91
                S:
                    - 3
                d:
                    - 192
                h:
                    - 256
                kset:
                    - - 5
                      - 3
        TinyTCN:
            grid:
                L:
                    - 91
                S:
                    - 3
                blocks:
                    - 3
                d:
                    - 192
                kset:
                    - - 5
                      - 3
num_workers:
    value: 8
out_dim:
    value: 2
path:
    value: C:\Users\ChanyoungKo\OneDrive - 한국과학기술원 기계공학과\Kyle\KAIST\ExoLab\Research and projects\2025_Intention Intelligence Team\NetworkCode\251030_combined_data.h5
patience:
    value: 5
prefetch_factor:
    value: 4
run_list:
    value:
        - TCN_GRU
        - GRU_Stack
        - TinyTCN
        - SmallTCN_LSTM_Attn
save_name:
    value: SE_GRU_Stack_L90_S3_h192_layers3.pt
save_prefix:
    value: SE_
sub_names:
    value:
        - S004
        - S005
        - S006
        - S007
        - S008
        - S009
        - S010
        - S011
test_subs:
    value:
        - S004
train_subs:
    value:
        - S007
        - S008
        - S009
        - S010
        - S011
use_conds:
    value:
        - accel_sine
        - cadence_120p
        - cadence_90p
        - decline_5deg
        - incline_10deg
        - level_08mps
        - level_12mps
        - level_16mps
val_batch_size:
    value: 1024
val_subs:
    value:
        - S006
weight_decay:
    value: 0.01
