shared:
  src_h5: ./combined_data.h5
  dst_h5: combined_data_speed_diff.h5
  subjects:
  - S001
  - S002
  - S003
  - S004
  conditions:
  - level
  - stopandgo
  input_vars:
  - - mocap/kin_q
    - - hip_flexion_l
      - hip_flexion_r
      - knee_angle_l
      - knee_angle_r
      - ankle_angle_l
      - ankle_angle_r
  output_vars:
  - - treadmill/left
    - - speed_leftbelt
  data: &id003
    window_size: 200
    stride: 5
    stride_inf: 1
    y_delay: 5
    est_tick_ranges: &id001
    - 5
    normalize: true
    time_window_output: 1
  model: &id002
    type: TCN
    channels:
    - 16
    - 16
    - 32
    - 32
    kernel_size: 7
    dropout: 0.5
    use_norm: true
    head_hidden:
    - 32
    head_dropout: 0.5
    model_norm: layer
    gating_signal: null
    attention_type: null
    attention_heads: 0
02_train:
  data:
    window_size: 200
    stride: 5
    stride_inf: 1
    y_delay: 5
    est_tick_ranges: *id001
    normalize: true
    time_window_output: 1
    normalize_type: standard
    use_physical_velocity_model: false
    use_gait_phase: false
  model: *id002
  train:
    task_type: regression
    loss: mse
    loss_penalty: frequency_cutoff_penalty
    loss_penalty_weight: 0.5
    loss_penalty_cutoff: reference
    epochs: 100
    lr: 0.001
    wd: 0.01
    amp: true
    device: cuda
    save_dir: ./runs_tcn
    early_stop_patience: 10
    early_stop_min_delta: 1e-03
    early_stop_warmup: 5
    k_fold: 4
    train_loss_target: 0.0
    kinematic_loss_weight_pos: 0.0
    augment_noise_std: 0.0
    kinematic_loss_weight_limit: 0
    kinematic_loss_degrees: false
    kinematic_loss_tolerance: 0.05
    smoothness_loss_weight: 0.0
    cos_T0: 10
    cos_Tmult: 1
    eta_min: 1.0e-05
  experiment_name: Exp_Freq_Penalty_Loss
03_eval:
  io_h5: combined_data_speed_diff.h5
  split:
    mode: manual
    level: subject
    seed: 42
    ratio:
    - 0.7
    - 0.15
    - 0.15
    manual:
      test:
      - S001
    save_to: null
  data: *id003
  train:
    device: cuda
  scaler_path: ./runs_tcn/scaler.npz
