exp_name: "Debug_IO_Test"
data_path: "combined_data.h5"
epochs: 1
batch_size: 256
tcn_channels: [32, 32]
lstm_hidden: 32
mlp_hidden: 32

# Custom Cost Function
cost_function: "mse"

# Custom Input Vars (Subset for testing)
input_vars:
  - ["robot/left", ["hip_angle"]]
  - ["robot/right", ["hip_angle"]]
  - ["forceplate/grf/left", ["z", "contact"]]

output_vars:
  - ["common", ["v_Y_true"]]
  
time_window_input: 100
cv_mode: "loso"
# Removed manual subject lists

# Dataset Definition (Universe)
subjects: ["S001", "S002", "S003", "S004", "S005", "S006", "S007", "S008"]
conditions: ["accel_sine", "decline_5deg", "incline_10deg", "level_075mps", "level_100mps", "level_125mps", "stopandgo"]
lpf_cutoff: 6.0
lpf_order: 5
