exp_name: exp_shallow_tcn
model:
  type: TCN
  channels:
  - 32
  - 64
  kernel_size: 3
  dropout: 0.1
data:
  use_complementary_filter_euler: false
shared:
  data_sources:
    milestone1:
      path: ./combined_data_milestone1.h5
      prefix: m1_
      exclude_subjects:
      - S001
      - S002
      - S003
    milestone2:
      path: ./combined_data.h5
      prefix: m2_
      exclude_subjects: []
  subjects:
  - m1_S004
  - m1_S005
  - m1_S006
  - m1_S007
  - m1_S008
  - m1_S009
  - m1_S010
  - m1_S011
  - m2_S001
  - m2_S002
  - m2_S003
  - m2_S004
  - m2_S005
  - m2_S006
  - m2_S007
  - m2_S008
  conditions:
  - level_08mps
  - level_12mps
  - level_16mps
  - level_075mps
  - level_100mps
  - level_125mps
  - accel_sine
  - decline_5deg
  - incline_10deg
  - stopandgo
  input_vars:
  - - robot/back_imu
    - - accel_x
      - accel_y
      - accel_z
      - gyro_x
      - gyro_y
      - gyro_z
  - - robot/left
    - - hip_angle
  - - robot/right
    - - hip_angle
  output_vars:
  - - mocap/kin_q
    - - hip_flexion_l
      - hip_flexion_r
  data:
    window_size: 200
    stride: 5
    stride_inf: 1
    y_delay: 0
    est_tick_ranges:
    - 0
    normalize: true
    time_window_output: 1
    use_complementary_filter_euler: false
  model:
    type: TCN
    channels:
    - 32
    - 64
    - 64
    - 128
    kernel_size: 5
    dropout: 0.5
    use_norm: true
    head_hidden:
    - 64
    head_dropout: 0.5
    model_norm: layer
    gating_signal: null
    attention_type: null
    attention_heads: 0
