epochs: 25
experiment_name: GS_017_Tiny_InNorm_TcnNo_LstmLN_W80
lpf_cutoff: 0.5
lstm_hidden: 32
lstm_use_ln: true
mlp_hidden: 32
mlp_norm: null
tcn_channels:
- 16
- 32
- 64
tcn_norm: null
time_window_input: 80
use_input_norm: true
