epochs: 25
experiment_name: GS_012_Tiny_NoIn_TcnBN_LstmLN_W100
lpf_cutoff: 0.5
lstm_hidden: 32
lstm_use_ln: true
mlp_hidden: 32
mlp_norm: null
tcn_channels:
- 16
- 32
- 64
tcn_norm: batch
time_window_input: 100
use_input_norm: false
