epochs: 25
experiment_name: GS_070_Medium_InNorm_TcnBN_LstmLN_W40
lpf_cutoff: 0.5
lstm_hidden: 128
lstm_use_ln: true
mlp_hidden: 128
mlp_norm: null
tcn_channels:
- 64
- 128
- 256
tcn_norm: batch
time_window_input: 40
use_input_norm: true
