epochs: 25
experiment_name: GS_062_Medium_InNorm_TcnNo_LstmNo_W80
lpf_cutoff: 0.5
lstm_hidden: 128
lstm_use_ln: false
mlp_hidden: 128
mlp_norm: null
tcn_channels:
- 64
- 128
- 256
tcn_norm: null
time_window_input: 80
use_input_norm: true
