epochs: 25
experiment_name: GS_035_Small_NoIn_TcnBN_LstmLN_W80
lpf_cutoff: 0.5
lstm_hidden: 64
lstm_use_ln: true
mlp_hidden: 64
mlp_norm: null
tcn_channels:
- 32
- 64
- 128
tcn_norm: batch
time_window_input: 80
use_input_norm: false
