epochs: 25
experiment_name: GS_019_Tiny_InNorm_TcnBN_LstmNo_W40
lpf_cutoff: 0.5
lstm_hidden: 32
lstm_use_ln: false
mlp_hidden: 32
mlp_norm: null
tcn_channels:
- 16
- 32
- 64
tcn_norm: batch
time_window_input: 40
use_input_norm: true
