epochs: 25
experiment_name: GS_045_Small_InNorm_TcnBN_LstmNo_W100
lpf_cutoff: 0.5
lstm_hidden: 64
lstm_use_ln: false
mlp_hidden: 64
mlp_norm: null
tcn_channels:
- 32
- 64
- 128
tcn_norm: batch
time_window_input: 100
use_input_norm: true
